version: '3.9'
services:
  langchain:
    image: langchain:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8000:8000
    env_file:
      - .env